name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semvers.outputs.v_minor }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        continue-on-error: true
        with:
          fallback: 1.0.0
          
      - name: Get next version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

  build:
    needs: version
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: Build Release
        run: cargo build --release
      
      - name: Create ZIP
        run: |
          cd target/release
          $version = "${{ needs.version.outputs.new_version }}"
          $exeName = "xrf-detection-postprocessor-${version}.exe"
          $zipName = "xrf-detection-postprocessor-${version}.zip"
          Copy-Item "xrf-detection-postprocessor.exe" -Destination $exeName
          7z a $zipName $exeName
          cd ../..
        shell: pwsh
        
      - name: Create Release
        uses: softprops/action-gh-release@v2.0.9
        with:
          tag_name: ${{ needs.version.outputs.new_version }}
          name: Release ${{ needs.version.outputs.new_version }}
          files: |
            target/release/xrf-detection-postprocessor-${{ needs.version.outputs.new_version }}.exe
            target/release/xrf-detection-postprocessor-${{ needs.version.outputs.new_version }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}