name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      
      - name: Build Release
        run: cargo build --release
      
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        continue-on-error: true
        
      - name: Calculate new version
        id: version
        run: |
          $previousTag = "${{ steps.previoustag.outputs.tag }}"
          if ([string]::IsNullOrEmpty($previousTag)) {
            echo "version=1.0" >> $env:GITHUB_OUTPUT
          } else {
            $previousVersion = $previousTag -replace 'v', ''
            $major, $minor = $previousVersion.Split('.')
            $newMinor = [int]$minor + 1
            $newVersion = "1.$newMinor"
            echo "version=$newVersion" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh
        
      - name: Create ZIP
        run: |
          cd target/release
          $version = "${{ steps.version.outputs.version }}"
          $exeName = "xrf-detection-postprocessor-v${version}.exe"
          $zipName = "xrf-detection-postprocessor-v${version}.zip"
          Copy-Item "xrf-detection-postprocessor.exe" -Destination $exeName
          7z a $zipName $exeName
          cd ../..
        shell: pwsh
        
      - name: Create Release
        uses: softprops/action-gh-release@v2.0.9
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          files: |
            target/release/xrf-detection-postprocessor-v${{ steps.version.outputs.version }}.exe
            target/release/xrf-detection-postprocessor-v${{ steps.version.outputs.version }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}