name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      
      - name: Build Release
        run: cargo build --release
        
      - name: Create ZIP
        run: |
          cd target/release
          7z a xrf-detection-postprocessor.zip xrf-detection-postprocessor.exe
          cd ../..
        shell: pwsh
      
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        continue-on-error: true
        
      - name: Calculate new version
        id: version
        run: |
          if ("${{ steps.previoustag.outcome }}" -eq "failure") {
            echo "version=1.0" >> $env:GITHUB_OUTPUT
          } else {
            $previousVersion = "${{ steps.previoustag.outputs.tag }}" -replace 'v', ''
            $major, $minor = $previousVersion.Split('.')
            $newMinor = [int]$minor + 1
            if ($major -eq "1" -and $minor -eq "9") {
              $newMinor = "10"
            }
            $newVersion = "1.$newMinor"
            echo "version=$newVersion" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          files: |
            target/release/xrf-detection-postprocessor.exe
            target/release/xrf-detection-postprocessor.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}